
trigger:
  - none
  
pool:
  vmImage: 'ubuntu-18.04'

name: $(BuildDefinitionName)_$(VersionNumber)_$(SourceBranchName)

stages:
- stage: BuildSetup
  displayName: Setup Build 
  jobs: 
  - job:
    steps:
      - task: PowerShell@2
        displayName: "Update Build Number"
        inputs:
          targetType: 'inline'
          script: |
              $BuildName = $env:BUILD_DEFINITIONNAME +'_'+$env:VERSIONNUMBER +'_'+ $env:BUILD_SOURCEBRANCHNAME 
              Write-Host "##vso[build.updatebuildnumber]$BuildName"
              steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
        displayName: 'Use Python 3.8'
    
      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        displayName: 'Install dependencies'


      - script: |
          python -m pip install --user --upgrade pip setuptools wheel twine bandit sphinx pytest pytest-mock pytest-cov black
        displayName: 'Install Tools'
    
      - script: |
          set PYTHONPATH=src
          pytest -v -x generatenunit.py 
        displayName: 'pytest'
  
      - task: PublishTestResults@2
        displayName: 'Publish Test Results **/_nunit_test_results.xml'
        inputs:
          testRunner: NUnit
          testResultsFiles: '**/_nunit_test_results.xml'
          failTaskOnFailedTests: true
    